### ISSUE TITLE
Automatic testing of your package

### ISSUE THREAD

**Issue by lcolladotor** [papaemmelab/ipssm#3]
Hi!

I just found out about this R package through #BoG22 https://twitter.com/lcolladotor/status/1524407243596353536. Congrats for your work!

From what I can see, your package is not tested right now. You might benefit from using a GitHub Actions workflow to test your package on several OS and help users use your software. See for example https://github.com/r-lib/actions or https://lcolladotor.github.io/biocthis/reference/use_bioc_github_action.html (disclaimer: I made it) if you have Bioconductor dependencies. 

You might also be interested in adding unit tests, for example, check https://r-pkgs.org/tests.html.

I'd be glad to chat about it if it helps http://lcolladotor.github.io/#contact. Louise @lahuuki or Josh @joshstolz from my team could also help through https://lcolladotor.github.io/bioc_team_ds/data-science-guidance-sessions.html#.YnvTbhPMKeA. 

Best,
Leo

**Comment by ElsaB** [comment]
Hi Leonardo

Best thanks for your message and suggestions.

Adding unit tests was on our todo list and the GitHub Actions workflow you
suggested looks great.
We'll have a look into and may get in touch indeed for further guidance!

Best
Elsa

**Comment by juanesarango** [comment]
Thanks @lcolladotor for the suggestion. And pointing to great resources! 

We are adding automated tests to the package in #5
